name: task-a ci

on:
  pull_request:
    paths:
      - 'task_a/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "pypy3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.10"

    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r ./task_a/requirements.txt
      - name: Run pytest
        run: |
          pytest ./task_a/task_a.py --html=report.html
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: Report-${{ matrix.os }}-${{ matrix.python-version }}
          path: report.html