name: task-b manual

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true
        default: 'Hello CI/CD'
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: "ubuntu-latest"
    name: Docker build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Replace message in index.html
        run: sed -i "s#DEFAULT_MESSAGE#${{ inputs.message }}#" ./task_b/index.html
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./task_b/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.tag }}

  test:
    runs-on: "ubuntu-latest"
    name: Test Docker container
    needs: docker
    services:
      test_container:
        image: ghcr.io/${{ github.repository }}:${{ inputs.tag }}
        ports:
          - 8080:80
    steps:
      - name: Wait for service to be ready
        run: |
          for i in {1..10}; do
            curl -sSf 127.0.0.1:8080/index.html && break || sleep 3
          done
      - name: Fetch index.html
        run: curl 127.0.0.1:8080/index.html